app.name: lianyihongdong
server:
  port: 8888
logging:
  path: .

spring:
  datasource:
    url: jdbc:mysql://47.92.158.149:8606/data?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1