app.name: lianyihongdong
server:
  port: 80
logging:
  path: .

spring:
  datasource:
    url: jdbc:mysql://47.92.158.149:8606/data?useSSL=false&useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none